# Settings for the left half
# They are combined with the settings from totem.conf
#

# Enable ZMK Studio support
CONFIG_ZMK_STUDIO=y

# Add battery reporting for second half
# https://zmk.dev/docs/config/battery#peripheral-battery-monitoring
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
